eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    hostname: localhost




 
microservice:
  microA:
    endpoints:
      endpoint:
        uri: http://MICROA/a/showA
  microB:
    endpoints:
      endpoint:
        uri: http://MICROB/b/showB   

    
